name: "SMZDM Checkin"

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '14 21 * * *'
  watch:
    types: [started]

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@master
    - 
      name: Go ENV
      uses: cedrickring/golang-action/go1.11@1.6.0
    - 
      name: Checkin
      env:
        GO111MODULE: "on"
        SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
        CHANIFY_TOKEN: ${{ secrets.CHANIFY_TOKEN }}
      run: go build -o checkin checkin.go && ./checkin
